### PR TITLE
Added LevelType enum to ModManager

### PR DESCRIPTION
**Pull request by AtiLion**

### CODE REVIEW

**Comment by Bluscream** [comment]
Why did you close it?

**Comment by Bluscream** [comment]
Is it not consistent? :thinking:

**Comment by AtiLion** [comment]
Slay wants it done a bit differently and messed one up anyway

**Comment by Bluscream** [comment]
i'll check the discord, thanka

**Comment by Bluscream** [comment]
Thanks* smh

**Pull request closed without merging**
